const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const CreateFormSchema = new Schema({
    owner: String,
    brojKategorija: String,
    kategorija1: String,
    kategorija1Tip: String,
    kategorija1Boja: String,
    kategorija2: String,
    kategorija2Tip: String,
    kategorija2Boja: String,
    kategorija3: String,
    kategorija3Tip: String,
    kategorija3Boja: String,
    kategorija4: String,
    kategorija4Tip: String,
    kategorija4Boja: String,
    Kategorija5: String,
    kategorija5Tip: String,
    kategorija5Boja: String,
    kategorija6: String,
    kategorija6Tip: String,
    kategorija6Boja: String,
    kategorija7: String,
    kategorija7Tip: String,
    kategorija7Boja: String,
    kategorija8: String,
    kategorija8Tip: String,
    kategorija8Boja: String,
    kategorija9: String,
    kategorija9Tip: String,
    kategorija9Boja: String,
    kategorija10: String,
    kategorija10Tip: String,
    kategorija10Boja: String,
    kategorija11: String,
    kategorija11Tip: String,
    kategorija11Boja: String,
    kategorija12: String,
    kategorija12Tip: String,
    kategorija12Boja: String,
    kategorija13: String,
    kategorija13Tip: String,
    kategorija13Boja: String,
    kategorija14: String,
    kategorija14Tip: String,
    kategorija14Boja: String,
    kategorija15: String,
    kategorija15Tip: String,
    kategorija15Boja: String,
    kategorija16: String,
    kategorija16Tip: String,
    kategorija16Boja: String,
    kategorija17: String,
    kategorija17Tip: String,
    kategorija17Boja: String,
    kategorija18: String,
    kategorija18Tip: String,
    kategorija18Boja: String,
    kategorija19: String,
    kategorija19Tip: String,
    kategorija19Boja: String,
    kategorija20: String,
    kategorija20Tip: String,
    kategorija20Boja: String,
});

module.exports = mongoose.model("CreateForm", CreateFormSchema);
